data=read.csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
View(data)
library(dplyr)
data %>%
group_by(PhoneService) %>%
summarise(proportions=n()/nrow(PhoneService)
)
prop.table(table(data$PhoneService))
prop.table(table(data$InternetService))
subset(data, data$churn == "Yes")
prop.table(table(data$Churn,data$tenure))
prop.table(table(data$tenure,data$Churn))
library(ggplot2)
n=mean(data$tenure[data$Churn=="Yes"])
n
n2=mean(data$tenure[data$Churn=="No"])
n2
library(ggcorrplot)
library(corr[])
library(corrplot)
corrplot(data$Churn,method = "color")
corr=round(cor(data),1)
df=dplyr::select_if(data,is.numeric)
r=cor(df,use = data$Churn)
r=cor(df,use ="complete.obs")
round(r,2)
ggcorrplot(r)
data$Churn=as.factor(mapvalues(data$Churn,from=c("No") to=c(0)))
data$Churn=as.factor(mapvalues(data$Churn,from=c("No"),to=c(0)))
library(dplyr)
data$Churn=as.factor(mapvalues(data$Churn,from=c("No"),to=c(0)))
data$Churn=as.factor(plyr::mapvalues(data$Churn,from=c("No"),to=c(0)))
data$Churn=as.factor(plyr::mapvalues(data$Churn,from=c("Yes"),to=c(1)))
df=dplyr::select_if(data,is.numeric)
r=cor(df,use ="complete.obs")
round(r,2)
ggcorrplot(r)
class(data$Churn)="Numeric"
> df=dplyr::select_if(data,is.numeric)
df=dplyr::select_if(data,is.numeric)
r=cor(df,use ="complete.obs")
df=dplyr::select_if(data,is.numeric)
r=cor(df,use ="complete.obs")
class(data$Churn)="numeric"
df=dplyr::select_if(data,is.numeric)
r=cor(df,use ="complete.obs")
r=cor(df,use ="complete.obs")
class(data$Churn)
data$Churn=as.factor(plyr::mapvalues(data$Churn,from=c("No"),to=c(0.0)))
data$Churn=as.factor(plyr::mapvalues(data$Churn,from=c(0),to=c(0.0)))
data$Churn=as.factor(plyr::mapvalues(data$Churn,from=c(1),to=c(0.0)))
data$Churn=as.factor(plyr::mapvalues(data$Churn,from=c(2),to=c(1.0)))
class(data$Churn)
data$Churn=as.numeric(plyr::mapvalues(data$Churn,from=c(2),to=c(1.0)))
data$Churn=as.numeric(plyr::mapvalues(data$Churn,from=c(1.0),to=c(1)))
data$Churn=as.numeric(plyr::mapvalues(data$Churn,from=c(0.0),to=c(0)))
data$Churn=as.numeric(plyr::mapvalues(data$Churn,from=c(1),to=c(0)))
data$Churn=as.numeric(plyr::mapvalues(data$Churn,from=c(2),to=c(1)))
class(data$Churn)
df=dplyr::select_if(data,is.numeric)
r=cor(df,use ="complete.obs")
round(r,2)
ggcorrplot(r)
barplot(prop.table(table(data$PhoneService),margin=1))
library(ggplot2)
barplot(y,n.margin=1)
barplot(y,n,margin=1)
ggplot(mapping = aes(x=y,y=n))+geom_bar()
ggplot(mapping = aes(x=y,y=n))+geom_bar(stat = identity())
ggplot(mapping = aes(x="y",y="n"))+geom_bar()
ggcorrplot(r)
ggplot(mapping = aes(x=mean(data$tenure[data$Churn=="Yes"]),y=mean(data$tenure[data$Churn=="No"])))+geom_point()
